zclconf/go-cty

cty/unknown_as_null.go, cty/unknown_as_null_test.go
If a null object type is passed in, we need to return early in order to
prevent using ElementIterator on a null value.
=> return nulls early from UnknownAsNull

cty/msgpack/unmarshal.go
While a length of 0 should be an empty value, a length of -1 indicates
a null or missing value, and we should return a NullVal.
=> handle missing values during unmarshal

cty/value_ops.go, cty/value_ops_test.go
If only one value is Null regardless of type, then the result must be
False.
=> handle more null values in Equals

cty/convert/conversion.go, cty/convert/public_test.go
When the conversion output is DynamicPseudoType, don't convert null
values, as the output type doesn't matter and we lose the only
information available for comparison.
=> Don't convert null values to cty.DynamicPseudoType

cty/json/type_implied.go, cty/json/type_implied_test.go
This is valid, yet unsupported JSON:
```
[
{"true": true}
]
```
=> Support lists of objects

cty/value_ops.go, cty/value_ops_test.go
All null values should compare equal regardless of type. RawEquals will
remain for strict type comparison.
=> consider all Null values equal in Equals

cty/gocty/out.go, cty/gocty/out_test.go, cty/path.go
Each commit is discrete, happy to open multiple PRs if you prefer (or just close this if you aren't interested).
=> gocty type alias support

cty/convert/conversion_collection.go, cty/convert/public_test.go
Converting an empty tuple value to a set should result in an empty set, not an
empty list.
=> convert empty tuple to empty set

cty/diff/change.go, cty/diff/diff.go, cty/diff/diff_test.go
Currently `diff.Apply` returns an error `not yet implemented`.
The comment https://github.com/zclconf/go-cty/pull/18#issuecomment-485941933 states _"This diff package is, to be honest, kinda abandoned at this point"_ but it is more focused on the diff printing aspect, rather than applying a diff to update values. I have a use-case for applying changes to a `cty.Value` and the diff package fits the bill perfectly. As the code is 2 years old, i'm not expecting it to be implemented any time soon, if at all.
This PR implements [`diff.Apply()`](https://github.com/zclconf/go-cty/blob/4fecf87372ec204b46eb9e8ff264cdc3cafdccfe/cty/diff/diff.go#L39-L41), and i think it is _(mostly)_ correct. The implementation adds an `apply` method on the [`Change …
=> cty/diff: implement diff package

cty/path.go, cty/path_test.go
Paths comparisons done with reflect.DeepEqual may erroneously return
false for numeric IndexSteps, due to the differences in the internal
values of the big.Float.
=> implement Path.Equals and Path.HasPrefix

cty/gob.go, cty/gob_test.go, cty/set_internals.go, cty/set_internals_test.go
We previously had a more localized workaround for this that worked only for numbers directly, but it failed to deal with the same problem in situations where the number is embedded inside some other compound type.
Now we'll apply the fix recursively over the whole raw decoded data structure from gob, finding and fixing numbers inside all of the structural and collection types too.
Although this fixup is mostly contained within the gob-handling functions, it does bleed slightly into the set internals because otherwise we get a chicken/egg problem where gob decoding of a set of numbers fails before we get a chance to run the fixup.
The JSON and msgpack encodings of cty are the primary supported serialization formats for the standard cty type system and I'd still recommend using those …
=> cty: Fix panics with gob encoding of values containing numbers

cty/convert/conversion_primitive.go
In case, when a bool string contains `True` or `False`, the conversion doesn't work.
see https://github.com/terraform-providers/terraform-provider-openstack/issues/924
=> Make a bool conversion error more verbose

cty/marks.go, cty/value_init_test.go, cty/walk_test.go
This fixes the following stack overflow as demonstrated in the attached test.
```
runtime: goroutine stack exceeds 1000000000-byte limit
fatal error: stack overflow
runtime stack:
runtime.throw(0x12c7621, 0xe)
/Users/radeksimko/.goenv/versions/1.12.9/src/runtime/panic.go:617 +0x72
runtime.newstack()
/Users/radeksimko/.goenv/versions/1.12.9/src/runtime/stack.go:1041 +0x6f0
runtime.morestack()
/Users/radeksimko/.goenv/versions/1.12.9/src/runtime/asm_amd64.s:429 +0x8f
...
```
=> SetVal: Fix stack overflow in umarking logic

cty/convert/conversion.go, cty/convert/conversion_collection.go, cty/convert/public_test.go
Allow conversions from maps to objects.
We return a conversion when the map element type con convert to all
possible attributes. The conversion itself will fail if the map contains
keys that are not valid attributes of that object type.
=> add conversion for map to object

cty/convert/conversion_collection.go, cty/convert/public_test.go, cty/convert/unify.go
When converting an object tree to a nested dynamic map (for example, `cty.Map(cty.Map(cty.DynamicPseudoType))` or deeper), it is necessary to unify the types of the child elements of the map.
Previously, we would only apply this process to the innermost leaf object's attributes, which could result in local unification but globally incompatible types. This caused a panic when converting the single top-level object into a map with concrete type, as the types of the sub-trees were incompatible.
This commit addresses this class of bugs in two ways: adding type unification for multi-level map and object structures, and fallback error handling to prevent panics for this class of failure.
The additional type unification process has several steps:
- First, we add a second unify & convert step at …
=> convert: Fix converting to nested dynamic map

cty/function/stdlib/collection.go, cty/function/stdlib/collection_test.go
Contains was transferred from Terraform, but the Index function which it
was calling has the inverse meaning than the Terraform function.
=> fixed Contains stdlib function

cty/function/stdlib/string.go, cty/function/stdlib/string_test.go
This issue was raised in terraform (hashicorp/terraform#24318) and it looks like it's a bug in `stdlib.SubstrFunc`'s impl where the substr function returns the whole string then the `length` argument is 0.
I've got a fix which is hopefully useful, I thought that it'd be best to have the `length` check as high up as it can but there may be other factors I'm not considering (I've run the test suite and it's passing).
=> Fix Substr function call with length argument of zero to return ""

cty/function/stdlib/number.go, cty/function/stdlib/number_test.go
`floor(±infinity)` and `ceil(±infinity)` would previously return the max/min limit of `int64`. This could lead to confusing behaviour. Instead, we want to pass through the infinite value without converting to integer.
From https://github.com/hashicorp/terraform/issues/21463
=> function/stdlib: Preserve infinity for floor/ceil

cty/path.go, cty/path_test.go
Add `int`/`string` helpers to the Index path convenience methods.
It would be kinda breaking, but may also be nice to change all of the convenience methods to be variadic? Maybe that's just overkill, UX wise you are probably only dealing with 1-2 depth at a time.
=> Add additional path convenience methods

cty/convert/conversion_collection.go, cty/convert/public_test.go
When converting a list of objects, it is necessary to unify the types of
the child elements. Previously `Convert` would panic if the nested objects had inconsistent element types.
This PR is nearly identical to #47, but handles lists of objects.
=> convert: fix panic when converting nested objects

cty/function/stdlib/set.go, cty/function/stdlib/set_test.go, cty/gocty/in_test.go, cty/path_set.go, cty/set/rules.go, cty/set/rules_test.go, cty/set/set.go, cty/set_internals.go, cty/set_internals_test.go
Two changes here to fix panics when using the `stdlib` set functions (`setintersect`, `setunion`, etc) where one of the parameters is an empty collection.
Previously, we checked if two sets had the same rules using a simple equality check. This panics if the sets contain object types, as they cannot be compared using `==`.
Adding an `Equals` method to the `Rules` interface allows us to delegate to the `Type.Equals` method where necessary, fixing this problem.
If one or more arguments to the `stdlib` set functions was an empty set of dynamic pseudo type, the functions would panic due to incompatible set rules.
We can special case empty dynamic pseudo type sets to be ignored through type unification, because they are always capable of being converted to any other type.
This PR fixes this …
=> Fix set function unification

cty/function/stdlib/json.go, cty/function/stdlib/json_test.go
This addresses https://github.com/hashicorp/terraform/issues/23062, where `jsonencode` does not allow null values, but it is documented in Terraform that it does: https://www.terraform.io/docs/configuration/functions/jsonencode.html. 
Terraform currently uses this zclconf edition of the go-cty library, but if this change is unwarranted here, perhaps it would be a better fit to migrate Terraform to https://github.com/hashicorp/go-cty and make changes there.
=> Allow null values for jsonencode

cty/convert/conversion_collection.go, cty/convert/public_test.go
Tuples with elements of different types can be converted to homogeneous collections (sets or lists), so long as their elements are unifiable. For example:
```hcl
toset(["a", "b"])     // all elements have the same type
toset(["a", 5])       // "a" and 5 can be unified to string
toset(["a", 5, null]) // null is a valid value for string
```
However, tuples with elements which are not unifiable cannot be converted to homogeneous collections:
```hcl
toset([["a"], "b"])   // no common type for list(string) and string
```
This commit fixes a panic for this failure case, when the tuple contains both non-unifiable types and a null value:
```hcl
toset([["a"], "b", null]) // should not panic
```
The null value was causing the unification process to result in a list or set of dynamic type, which …
=> convert: Fix panic: heterogeneous tuple with null

cty/type.go, cty/type_test.go, cty/value.go, cty/value_ops.go, cty/value_ops_test.go
When checking for nested dynamic types within complex types for equality comparison, we need to also verify that those dynamic types are not already known to be null.
Add the `Value.HasWhollyKnownType` method, to check for nested `DynamicVal` values. `HasWhollyKnownType` indicates not only that this value is not wholly known, but the type may change as well; as opposed to `HasDynamicTypes`, which only indicates that `DynamicPseudoType` exists within the type. This is used in the `Value.Equals` method before checking the type for equality.
Even when a value contains `DynamicVal`, we may still be able to check for inequality if the types are not conformant.  Check `TestConformance` in both directions to see if there is any possibility of the types later becoming equal.
This also fixes a bug …
=> A null dynamic value is a known value when comparing equality

cty/function/stdlib/collection.go, cty/function/stdlib/collection_test.go
Passing empty maps to MapVal panics. If we have an empty map after merging maps, return `MapValEmpty` so that we avoid this panic. Fixes https://github.com/hashicorp/terraform/issues/25303
=> Allow empty maps to merge function

cty/function/stdlib/set.go, cty/function/stdlib/set_test.go
[The fix for set unification](https://github.com/zclconf/go-cty/pull/52/files) recently introduced a bug with unknown set values which would cause a panic (hashicorp/terraform#25318). This was triggered by calling `LengthInt` on an unknown collection.
This commit fixes this by first verifying that the argument is known, so that calling its length is safe. If the argument is not known, it could be of any length, so we do not want to omit its element type from the set to be unified.
Includes regression tests.
Fixes hashicorp/terraform#25318
=> function/stdlib: Fix panic with unknown set values

cty/function/stdlib/collection.go, cty/function/stdlib/collection_test.go
This adds a check for a negative index to both Type Impl functions, and
some basic tests.
Downstream issue reference: https://github.com/hashicorp/terraform/issues/25775
=> funcs/element: fix panic when used with negative index

.travis.yml
Tests can't run on 1.11 and 1.12 (something something go modules) so I removed those and added a line for 1.13 (leaving `tip` in place for the next version of go).
=> build: remove go 1.11 and 1.12 from travis config

cty/value_ops.go, cty/value_ops_test.go
`RawEquals` should return true when comparing sets with the same type and same unknown values.
I've copied all the tests from `Equal` (modified to match the expected result of RawEquals) - the only test that was failing before this change is this one:
```
{
ObjectVal(map[string]Value{
"a": SetVal([]Value{
ObjectVal(map[string]Value{
"b": UnknownVal(String),
}),
}),
}),
ObjectVal(map[string]Value{
"a": SetVal([]Value{
ObjectVal(map[string]Value{
"b": UnknownVal(String),
}),
}),
}),
true,
},
```
I've also verified that this change doesn't cause any test failures in terraform.
=> RawEquals: Sets with the same unknowns are equal enough for RawEquals

cty/json/marshal.go, cty/marks.go, cty/marks_test.go, cty/msgpack/marshal.go
This PR adds two methods: `UnmarkDeepWithPaths`, `MarkWithPaths`, and the type `PathValueMarks` which is used in both methods. This allows a caller to call a method like Unmark, but instead of getting a superset of marks, get an array of marks and their associated paths. This allows for a Value to be unmarked and then remarked later.
Additional change: The error messages in `marshall` had a typo, and the JSON error was ambiguous, so the raised error would not make it clear that it was an error in JSON marshalling vs msgpack.
=> Add Unmark utilities

cty/marks.go, cty/marks_test.go, cty/value_init.go, cty/walk.go, cty/walk_test.go
The `UnmarkDeep`, `UnmarkDeepWithPaths`, and `MarkWithPaths` functions could previously panic with nested complex values. This was due to the `Transform` callback function only being called as part of a postorder traversal, when it is not permitted to traverse a marked value.
This commit introduces a new `TransformWithTransformer` function, requiring an implementation of a new `Transformer` interface. Using this interface, callers can implement either preorder or postorder traversals.
In turn, this allows us to write deep transformation for marks which successfully cope with all nested structures.
The commit includes significantly more tests for these functions, which should now cover all complex value types.
=> Fix deep marks functions with new transformer

cty/function/stdlib/datetime.go, cty/function/stdlib/datetime_test.go
Fixes Terraform bug https://github.com/hashicorp/terraform/issues/26356
I haven't raised a corresponding issue here, it just seemed like duplication of effort - hope that's ok.
It's end of day here and I'm AFK tomorrow so if there are any issues or changes requested I will be able to look on Friday.
=> Ensure splitDateFormat() does not try to look for more bytes when we are at EOF

cty/marks.go, cty/marks_test.go, cty/walk.go
When unmarking a complex value and retaining the marked paths, a sufficiently deep structure would result in incorrect duplicate path output. For example, this structure (in HCL syntax):
```hcl
{
environment = [
{
variables = {
"x" = 1
"y" = 2
}
}
]
}
```
If the 1 and 2 values are marked, the resulting path value marks from `UnmarkDeepWithPaths` would have two entries, as expected. However, both would have the same `Path` attribute, like so:
```text
[
{ environment[0].variables["x"], "mark" },
{ environment[0].variables["x"], "mark" },
]
```
This is caused by calling `append` in the walk transform function with the same path object repeatedly, which eventually does not result in array reallocation, and therefore the path object is modified in-place.
=> cty: Fix path array reuse with UnmarkDeepWithPaths

cty/function/function.go, cty/function/stdlib/string_test.go
For functions which do not explicitly support marks, we now deeply unmark arguments before calling, and reapply those marks to the return value. This ensures that these functions do not panic with arguments which are collection values with marked descendants.
This does result in overly conservatively applying marks in some cases, but that can be fixed with later work to add explicit support for marks to those functions.
I've added tests for the `join` function, which I now think exhibits the correct behaviour.
Replaces #71
=> function: Deeply unmark function arguments before calling, reapply afterwards

cty/type.go, cty/type_test.go
This is useful in combination with https://github.com/zclconf/go-cty-debug and https://github.com/google/go-cmp when comparing structs which may have `cty.Type` field which is optional, i.e. `NilType` is a valid value in that particular context.
=> Type.Equals: prevent crash when comparing NilType

cty/value_ops.go, cty/value_ops_test.go
There are probably other places where arbitrarily large values can
overflow the default precision creating unexpected results, but
these two points are the easiest to encounter. There is also
the issue that many functions drop down to operating on native float64
or int  internally (`floor`, `log`, `pow`, etc.). I chose to only handle
the `Multiply` and `Modulo` functions at this time, since they were
already using arbitrary precision values throughout.
- Do not lose precision in module function:
When working with big.Float values, it is imperative to ensure the
desired precision for the operations is maintained throughout. The
default precision for a Float is set initially by the max argument
precision when creating the non-zero value. If this is coming from a
Float which was set via …
=> maintain big.Float precision with multiplication and modulo

cty/convert/mismatch_msg.go, cty/convert/mismatch_msg_test.go
When determining which object attributes cause a type mismatch, we must disregard equal attribute types. Previously we would attempt to find a conversion between them, deciding that the attribute type was a mismatch if no conversion exists. However, this is invalid if the two types are equal, because `GetConversion` returns `nil` for equal primitive types.
Because of non-deterministic map iteration order, the test case added in this commit failed approximately 2/3 of the time before the change. It now passes consistently.
Terraform issue report: hashicorp/terraform#27010
=> convert: Fix MismatchMessage for object attributes

cty/function/stdlib/collection.go, cty/function/stdlib/collection_test.go
It seems intuitive for merge() to return an empty object when the inputs
are null (or omitted entirely) - returning an error would likely break
many terraform configurations, and returning an empty object rather than
null seems more consistent with the documented behavior (though it is
not explicit!).
I dug through the commit history and compared terraform's documentation,
post pre- and post-hcl2, and did not find any clues as to why it was
returning null rather than an empty object. I feel like this is an
acceptable breaking change, but am certainly open to other opinions.
=> functions/stdlib/merge: return an empty object when all inputs are null

cty/function/stdlib/collection.go, cty/function/stdlib/collection_test.go
The `coalescelist` function was moved here from hashicorp/terraform in #37. While [the Terraform function documentation doesn't specify whether or not `null` arguments are permitted](https://www.terraform.io/docs/configuration/functions/coalescelist.html), the implementation does allow them: https://github.com/zclconf/go-cty/blob/4a538861ac5cc80538f5aac666ba6f2b85d0af10/cty/function/stdlib/collection.go#L205-L213
However as reported in https://github.com/hashicorp/terraform/issues/26988, passing a `null` argument causes a panic. This commit fixes the crash and adds test coverage for the function.
=> Fix CoalesceList panic when passed null arguments

cty/object_type.go, cty/type_test.go
The returned `GoString()` for a `cty.ObjectWithOptionalAttrs` was a bit off;
the returned slice of optional attributes was twice as long as it needed
to be due to a mismatch where the slice was created with make, but then
appended to (as opposed to indexed into).
I didn't see test coverage for `Type` `GoString()`, so I copied the test cases from Value's `GoString()` (fewer test cases, since I didn't need to differentiate between null and empty values). Here's the related test before the fix:
```--- FAIL: TestTypeGoString (0.00s)
--- FAIL: TestTypeGoString/cty.ObjectWithOptionalAttrs(map[string]cty.Type{"bar":cty.String,_"foo":cty.Bool},_[]string{"",_"bar"}) (0.00s)
type_test.go:147: wrong result
got:  cty.ObjectWithOptionalAttrs(map[string]cty.Type{"bar":cty.String, "foo":cty.Bool}, …
```
=> Fix Object GoString()

cty/convert/conversion.go, cty/convert/public_test.go, cty/convert/unify.go, cty/type.go, cty/type_test.go
Two commits addressing issues related to objects with optional attributes. These commits address these downstream bugs in Terraform:
- https://github.com/hashicorp/terraform/issues/27269
- https://github.com/hashicorp/terraform/issues/27295
Conversions targeting types which are or include objects with optional attributes always simplify those types, removing the optional attributes from the type, and inserting null values for any that are missing.  Objects with optional attributes are not intended to be used to instantiate values.
One accidental exception to this was the null value of dynamic type.  These values are passed through by the getConversion wrapper, assigning the desired type. This conflicts with the type simplification rules for non-null values, and can result in a panic when …
=> Optional attributes fixes

cty/convert/unify.go, cty/convert/unify_test.go
Tuple and list unification is a common case due to the fact that list data is often in tuple form, either because of configuration language constructs or functions that must deal with possibly heterogeneous collections. In the current code, we would immediately fall back to type conversion, which has different semantics from type unification. The problem is most obvious when the tuples contains objects (which are often maps is disguise for the same reason that lists and tuples are interchanged), and the objects go through type conversion rather than type unification, where unsafe conversion can yield objects with only the intersection of attributes rather than a unified map.
Instead of falling back to direct conversion when there are only tuples and lists involved, we stay in the …
=> convert: unify tuples as lists and objects as maps when possible

cty/convert/conversion_collection.go, cty/value_init.go, cty/value_init_test.go
The logic which may result in a panic in List(), Map() and Set() have been extracted into these helper functions, which return errors instead. The original callers (still) panic if an error is returned.
These new functions are called in the appropriate conversion functions in the convert package to validate that the given elements can be used to create a single Type, to help reduce the number of panics that occur when calling Convert.
For additional background information on the (odd) scenarios that can lead to these panics, see https://github.com/hashicorp/terraform/issues/26195
While working on this, I realized that `conversionCheckMapElementTypes` was doing much the same thing, so I removed it in favor of `CanMapFunc()`. However since the logic for CanMapFunc() was taken from Map(), …
=> cty: add CanListFunc, CanSetFunc, CanMapFunc

cty/function/function.go, cty/function/function_test.go
`ReturnTypeForValues` was only checking an unmarking the top level value
for `TypeFunc`s that did not expect marked values. Use `ContainsMarked` and
`UnmarkDeep` to prepare the arguments.
=> function: don't pass unexpected marked values to TypeFunc

cty/function/stdlib/collection.go, cty/function/stdlib/collection_test.go
Previously `ValuesFunc` was just using the safe default behavior where if any argument contains any marked values at all then the result is automatically given the same marks.
That's valid but overly conservative, because it means that an unmarked map with a single marked element value will become a wholly-marked list result, rather than an unmarked list with one marked element value.
Now we'll opt in to custom mark handling within the function itself, and handle shallowly the marking of the overall collection -- propagating it to the result -- while letting the values inside retain their individual markings as needed.
We were previously lacking unit tests for the values function, I think because it's a pretty old one from when `cty` was new, so this also includes additional test cases …
=> function/stdlib: ValuesFunc precise handling of marks

cty/function/stdlib/collection.go, cty/function/stdlib/collection_test.go, cty/marks.go, cty/marks_test.go, cty/value_ops.go, cty/value_ops_test.go
`ZipmapFunc` can now handle marks on an element-by-element basis, to the extent that the `cty` type system is able to do so.
Since map keys can't be individually sensitive, any sensitive values in the keys list will aggregate on the map as a whole, but the individual value elements will have their marks preserved individually.
We previously didn't have unit tests for `ZipmapFunc` so this also includes some additional tests not related to marks, in order to cover the other interesting cases this function must handle.
---
Writing the tests for this also exposed some bugs in the `cty` package's handling of marks, and so I've fixed them as additional commits here.
=> function/stdlib: ZipmapFunc precise mark handling

cty/function/stdlib/sequence.go, cty/function/stdlib/sequence_test.go
`ConcatFunc` will now only mark the resulting list with marks from the argument lists as a whole, and not aggregate individual list element marks at the top-level result.
The individual element marks will still be preserved, but they'll remain attached to the individual element values they came from, avoiding the result as a whole becoming marked.
=> function/stdlib: ConcatFunc precise handling of marks

cty/function/stdlib/collection.go, cty/function/stdlib/collection_test.go
Two changes:
* Add AllowMarked: true
* Re-apply top-level marks to result
If the entire map is marked, those marks are applied to the resulting list of keys. Inner marks are not preserved (only _values_ can have marks).
=> function/stdlib/keys: accept marked arguments

cty/function/stdlib/collection.go, cty/function/stdlib/collection_test.go
Will now preserve markings on individual input elements, without aggregating them on the returned top-level list.
Marks on the list or on the chunk size will still propagate to the top-level return value.
`Chunklist` previously didn't have any tests, so I've added some here in addition to the coverage for the mark handling. I also did some light reorganization so that the argument error handling happens before any of the short-circuit return paths.
=> function/stdlib: ChunklistFunc precise mark handling

cty/function/stdlib/collection.go, cty/function/stdlib/collection_test.go
`MergeFunc` will now only mark the resulting map or object with marks from the given maps or objects as a whole, and not aggregate individual element/attribute marks at the top-level result.
The individual element/attribute marks will still be preserved, but they'll remain attached to the individual values they came from, avoiding the result as a whole becoming marked.
`FlattenFunc` will now propagate marks from lists/sets/tuples which are flattened to the top level result. Marks on non-flattened elements are retained and not assigned to the resulting collection.
There is a significant change to the flattener helper function to ensure that marks are propagated from all nested lists/sets/tuples, even after first encountering an unknown collection. Previously finding an unknown collection …
=> Merge, flatten, length, lookup functions: more precise handling of marks

cty/function/stdlib/collection.go, cty/function/stdlib/collection_test.go
Setproduct will now preserve marks on both the arguments and their elements. Marks that apply to any entire argument will propegate to all return values, while marks applied to a single element will remain attached to individual values.
=> function/stdlib: Setproduct mark handling

cty/function/stdlib/collection.go, cty/function/stdlib/collection_test.go
Hi!
This PR fixes: https://github.com/zclconf/go-cty/issues/102
When one of the argument of `setproduct` is an empty list, we would get this panic: 
```
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestSetproduct$ github.com/zclconf/go-cty/cty/function/stdlib
--- FAIL: TestSetproduct (0.00s)
--- FAIL: TestSetproduct/Setproduct([]cty.Value{cty.ListValEmpty(cty.EmptyObject),_cty.ListVal([]cty.Value{cty.StringVal("quick"),_cty.StringVal("fox")})}) (0.00s)
/Users/matthieu/Documents/projects/oss/go-cty/cty/function/stdlib/collection_test.go:2187: unexpected error: panic in function implementation: runtime error: hash of unhashable type cty.ValueMarks
goroutine 8 [running]:
runtime/debug.Stack(0xc0000746c8, 0x12b5120, 0xc00015d3c0) …
```
=> Fix panic in setproduct when one of the arguments is an empty list

cty/function/stdlib/collection.go, cty/function/stdlib/collection_test.go
ElementFunc, ReverseListFun and SliceFunc have been updated to handle marks, with tests!
=> ElementFunc, ReverseListFun and SliceFunc mark handling

cty/function/stdlib/collection.go, cty/function/stdlib/collection_test.go
If any type with the `flatten` argument is unknown, then the result cannot be known.
=> flatten must return unknown with dynamic vals

cty/function/stdlib/collection.go, cty/function/stdlib/collection_test.go
Using HasDynamicTypes to see if the Flatten argument's type will be
unknown is a little too conservative, and will also catch dynamic values
within maps and objects. Check each value as we're iterating to find any
dynamic values, relaxing the check imposed by #106.
=> Check each element for dynamic types in flatten

cty/function/stdlib/sequence.go, cty/function/stdlib/sequence_test.go
If concat is building a tuple type, it will need to check the length of
the arguments which requires unmarking the values.
=> concat may need to check length with marked vals

cty/function/stdlib/collection.go, cty/function/stdlib/collection_test.go
If an argument to `setproduct` is a set with unknown values, its length is unknown, as the unknown values may be duplicates of others in the set. This should result in returning an unknown value propagating all marks.
Previously this crashed due to a misuse of `.Mark(marks)` instead of `.WithMarks(marks)`. This commit also fixes an issue with the previous logic, which would shortcut return and omit marks from any arguments after the set with unknown length.
Also includes a couple of tests for setproduct that were in my local working copy for some reason.
Downstream issue: https://github.com/hashicorp/terraform/issues/28984
=> function/stdlib: Fix setproduct bug with unknowns

cty/function/stdlib/number.go, cty/function/stdlib/number_test.go
Do not convert floor and ceil arguments to float64 internally so as to not lose precision.
This leaves `pow` and `log` as the remaining numeric function which convert to primitive types internally. Both of these are much more complex to implement (which is why they are not included in the `math/big` package itself). The precision offered by `float64` ius likely sufficient for most any log operation, so that probably just leaves `exp` as the last function which needs to be implemented.
=> use big.Float for floor/ceil

cty/function/stdlib/collection.go, cty/function/stdlib/collection_test.go
When flattening a list of arguments, the special case of a `null` dynamic value should not force the result to be unknown. We do not check directly for "IsKnown" here, because it is specifically the dynamic type which will cause `flatten` to become unknown, while unknown values alone can be preserved preserved.
https://github.com/hashicorp/terraform/issues/29099
=> flatten: only DynamicVal should cause flatten to become unknown, not a null dynamic value. 

cty/value_ops.go, cty/value_ops_test.go
Equals need to extract all marks from nested values, rather than just
the top level to avoid panicking during comparison.
=> cty: handle deep marks in Equals

cty/value_ops.go, cty/value_ops_test.go
Use `Float.Copy` in `AsBigFloat` to ensure that there is no shared data
between the mutable `*big.Float` and the `cty.Value` internal state.
Without the Copy, the given test will output:
```
original value changed from cty.NumberFloatVal(1.9) to cty.NumberIntVal(1)
```
=> cty: AsBigFloat does a shallow copy

cty/function/stdlib/format.go, cty/function/stdlib/format_test.go
When formatlist encounters a DynamicVal argument, it must return an
unknown result, as it cannot determine if that will be a single value
argument resulting in an unknown string, or a list to be formatted into
an unknown number of strings.
=> formatlist: a DynamicVal arg may be a list

cty/primitive_type.go
This fixes a performance issue when comparing large numbers to zero (or large positive numbers to large negative numbers). Without this check, the numbers are both converted to text, and string compared, which is costly if the numbers are large.
This patch provides a cheap early-exit option if the signs don't match, speeding up the cost of comparison to zero. As part of this, the .Modulo function calling .RawEquals [here](https://github.com/zclconf/go-cty/blob/main/cty/value_ops.go#L690-L692) should also have significantly improved performance (which was otherwise an expensive check for large numbers).
=> Sanity check signs of raw number before comparison

go.mod, go.sum
Request to update text library to non-vulnerable version v0.3.7. [CVE-2021-38561](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-38561)
Description from CVE
golang-x-text - Out-of-bounds Read
Explanation
The golang.org/x/text package is vulnerable due to an Out-of-bounds Read. The files and functions listed below do not properly handle index calculations when parsing formatted language tags. A remote attacker can exploit this behavior by supplying a specially-crafted language tag to trigger a panic, causing an application crash and ultimately a Denial of Service (DoS) condition.
Vulnerable File(s) and Function(s):
internal/language/language.go
ParseExtension()
ParseBase()
ParseScript()
ParseRegion()
ParseVariant()
internal/language/parse.go
Parse()
language/parse.go
Parse() …
=> Security vulnerability

cty/convert/unify.go, cty/convert/unify_test.go
The `unifyObjectTypesToMap` function was inadvertently called from the tuple-list unification function, which would panic since the value has no attributes.
The given test example is possible to speculatively unify, however we don't have a codepath to recursively unify these yet, so we will just fail to unify for now. This will fix the crashes in downstream consumers, allowing the possibility of working around the shortcoming by using more specific or different combinations of types.
=> fix typo causing a panic in tuple unification

cty/function/stdlib/collection.go, cty/function/stdlib/collection_test.go
Fixes https://github.com/hashicorp/terraform/issues/31376
=> check for typed nulls in flatten func

CHANGELOG.md, cty/convert/conversion_collection.go, cty/convert/public_test.go
For https://github.com/hashicorp/terraform/issues/31924
This PR makes the `Convert` function explicitly strip out any nested optional attributes from empty lists and sets as they are converted.
I added three unit tests, one each for `list`, `set` and `map`. Interestingly, `map` conversion works even without the change applied. I wonder if there's something else about the way maps work that means they're not affected by this. I've left the unit test in but haven't made any change to the `map` logic.
=> `convert`: Remove nested optional attributes when converting empty lists and sets

cty/convert/conversion_collection.go, cty/convert/public_test.go
When converting a map into an object, if any attributes/values were not compatible the whole conversion would fail.
If an attribute is not convertible then we check if it's optional. If it is optional, then we don't error right away. We record a nil converter for that attribute leaving us with three cases for each attribute:
1. No entry in the converters map at all, this means no conversion necessary (eg. string to string)
2. Non-nil entry in the converters map, this means a conversion is required but possible (eg. string to number)
3. Nil entry in the converters map, this means a conversion is required but not possible (eg. string to object)
Case 1 and Case 2 are covered already, and case 3 is introduced by this PR. Case 3 is only possible when we have found an optional attribute that is …
=> Allow maps to convert into objects when missing optional attributes are not compatible

cty/convert/conversion_object.go, cty/convert/public_test.go
Very similar change to https://github.com/zclconf/go-cty/pull/135
=> Strip optional attributes from null objects during conversion

cty/convert/conversion_collection.go, cty/convert/public.go, cty/convert/public_test.go
I've added test cases covering maps, lists, sets, and tuples and added checks for null values in the relevant conversion functions. I also added a general check that the conversion package won't skip removing optionals when the types match.
=> Remove optional attributes from null values in all collections

cty/function/argument.go, cty/function/function.go
This PR introduces a new field, `Description`, to the functions `Spec` and `Parameter` types. I've decoupled this from the actual backfilling of all descriptions, so we and the education team can iterate on the descriptions.
To be able to offer auto-completion of available functions and their signatures within the Terraform language server, we need a longer description for both a function and each parameter.
More information is available in the [TF-418: Support Functions in Language Server](https://docs.google.com/document/d/1ZAzEjEefop5NpyP-npKgtr_zj7xIsNxT_KMheZPphdc/edit) RFC.
* https://github.com/zclconf/go-cty/pull/136 backfills all the function & parameter descriptions for stdlib functions from `go-cty`
* After this PR gets merged, I plan to do a similar thing for the functions in …
=> Introduce description field for function & parameters

cty/convert/conversion_collection.go, cty/convert/public_test.go
Similar to the same recent checks for null values.
Fixes the root cause of https://github.com/hashicorp/terraform/issues/32152
=> Check empty collections for optional attributes

cty/function/stdlib/datetime.go, cty/function/stdlib/datetime_rfc3339.go, cty/function/stdlib/datetime_test.go
The Go `time` package's interpretation of RFC3339 has historically been too liberal to properly meet the specification due to reliance on the "parse by example" approach taken by time.Parse.
There was a custom strict RFC3339 parser added during the Go 1.20 development period but that was removed just before release due to backward compatibility concerns.
Since cty's goal is to only accept valid RFC3339 and its use of the Go standard library to achieve that was always an implementation detail, here we'll now just inline a slightly similified version of the strict RFC3339 parser that was briefly in stdlib and use that.
Although a variation of this strict parser will probably land in Go stdlib again eventually, the goal here is to decouple cty's behavior from the Go stdlib behavior so it …
=> function/stdlib: Use local RFC3339 parser

cty/path.go, cty/path_test.go
The return value of `HasIndex` can contain marks, so `IndexStep.Apply` must strip those marks before checking `True`.
=> Path.Apply panics with marked collections

cty/ctystrings/prefix.go, cty/msgpack/roundtrip_test.go, cty/msgpack/unknown.go
Serialising an unknown value with a string prefix refinement with a sufficiently long prefix will result in an error on deserialisation, since cty limits the size of the refinements blob to 1024 bytes.
This PR is an implementation of the approach described in https://github.com/hashicorp/terraform/issues/33464#issuecomment-1625670378 for getting around this. Of course we would have to truncate the value while deserialising as well, otherwise the value does not round-trip correctly.
@apparentlymart I'm assuming that we don't want to impose a limit on prefix length when constructing the refinement in the first place (nor does the RefinementBuilder seem to allow for this, as far as I can tell). Silently truncating the prefix during serialisation seems like it suffices to preserve …
=> msgpack: truncate long string prefix refinements

CHANGELOG.md, cty/ctystrings/prefix.go, cty/function/stdlib/format.go, cty/function/stdlib/string.go, go.mod, go.sum
Go 1.21 now supports Unicode 15. The go-textseg package has a new version supporting Unicode 15.
=> deps: update go-textseg to v15

cty/convert/conversion_dynamic.go, cty/convert/public_test.go
When converting an unknown map into an object with optional attributes, that object may have attributes which don't match the map element type. This conversion will be valid, but when building Null or Unknown values of that type we need to ensure all attributes have a valid type.
The fallthrough path for dynamicReplace when non-primitive types didn't match contained a cty.NilVal element type, which would result in an overall invalid type. We can use early returns to ensure there are no uninitialized values, and let the fallback use the original out type. Since at this point the types appear to not be convertible, we can assume they are from attributes which were skipped during conversion due to being optional, otherwise the conversion would not have been valid.
=> convert: prevent invalid types in dynamicReplace

cty/msgpack/marshal.go, cty/msgpack/roundtrip_test.go, cty/primitive_type.go, cty/value_ops_test.go
This is two related bugs merged into a single PR, but we can split this up if needed.
The first is that `Equals` uses the string formatting for number comparison, but the format depends on the precision of the `big.Float` which could be different even with equal numbers. While we rely on the formatting implementation for "fuzzy" matching of floats, integers can be compared exactly.
The related bug was in the compact floats implementation of msgpack. When setting `UseCompactFloats(true)`, the msgpack encoder uses the expression `float64(int64(n)) == n` to check if the number con be represented by an `int64`. this can fail for some values on certain architectures, because the result of a failed conversion is undefined and system dependent.
=> Large integer comparisons and msgpack encoding

cty/function/stdlib/collection.go
fixed documentation of `lookup()` function (defaultValue not being optional)
=> #123 fixed documentation of lookup() function

cty/marks_test.go, cty/walk.go, cty/walk_test.go
When descending into an object inside a Transformer, the marks from the outer object should not be applied to the attribute values. This follows the pattern used in other collection types, and ensures marks are stable across multiple transformations.
=> use unmarked val when Transform walks object attrs

cty/function/function.go, cty/function/function_test.go
If a function parameter does not AllowUnknown, the function Call method returns early with the appropriate unknown value, however it was missing any possible marks that were known from the given arguments.
Delay the early return slightly, so that all argument marks can be collected and applied to the unknown return value.
The early return value will still not include marks from parameters which have `AllowMarked`, since we cannot determine if the function would have passed those marks through or not. If a function needs more detailed handling of marks in the unknown case, the parameters should set both `AllowUnknown` and `AllowMarked` and handle the logic in the function implementation.
=> function: include marks when returning early

cty/convert/conversion.go, cty/convert/conversion_capsule_test.go
Currently when converting between two capsule types if `ConversionTo` returns `nil` then the conversion fails, even if the target type defines a suitable `ConversionFrom`.
<details>
<summary>Example</summary>
```go
package main
import (
"fmt"
"log"
"reflect"
"github.com/zclconf/go-cty/cty"
"github.com/zclconf/go-cty/cty/convert"
)
func main() {
myStringType := cty.CapsuleWithOps("MyString", reflect.TypeOf(""), &cty.CapsuleOps{
ConversionTo: func(dst cty.Type) func(cty.Value, cty.Path) (interface{}, error) {
// conversions to some types other than myIntType defined here
// returns nil when asked to convert to the myIntType
return nil
},
})
myIntType := cty.CapsuleWithOps("MyInt", reflect.TypeOf(0), &cty.CapsuleOps{
ConversionFrom: func(src cty.Type) func(interface{}, cty.Path) (cty.Value, …
```
=> Try ConversionFrom if ConversionTo returns nil

cty/convert/conversion_collection.go, cty/convert/public_test.go
We had previously fixed this for lists and sets in https://github.com/zclconf/go-cty/pull/135.
There's a [thread](https://github.com/zclconf/go-cty/pull/135#issuecomment-1273366490) in that PR that asks why not for maps as well. At the time the issue wasn't being reproduced for maps in the same way because maps perform a post-conversion unification [here](https://github.com/zclconf/go-cty/blob/main/cty/convert/conversion_collection.go#L168-L173). This was stripping the optional attributes out in the original test case for maps, explaining why we didn't see this in maps before.
The new test cases uses maps in a way that the unification logic isn't called (by only using empty maps without nesting) and now exposes the same problem.
@apparentlymart, I'm not sure if we also want to add the …
=> convert: strip optional attributes out of empty maps
